import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import "@rainbow-me/rainbowkit/styles.css";
// import { ClientProvider } from "@/providers/client.provider";
import { headers } from "next/headers"; // added
import ContextProvider from '@/context/index'

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recobro : Lost and Found SAAS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = headers().get('cookie')
  return (
    <html lang="en" className="relative" suppressHydrationWarning>
      <body className={twMerge(dmSans.className, "antialiased bg-[#EAEEFE]")}>
      <ContextProvider cookies={cookies}>{children}</ContextProvider>
      </body>
    </html>
  );
}
