import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import "@rainbow-me/rainbowkit/styles.css";
import { ClientProvider } from "@/providers/client.provider";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recobro : Lost and Found SAAS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative" suppressHydrationWarning>
      <body className={twMerge(dmSans.className, "antialiased bg-[#EAEEFE]")}>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
